### ISSUE TITLE
Is "no_reg_lbfgs.jar" in "jars" folder a Compilation of Forclift’s Original Code?

### ISSUE THREAD

**Issue by SeongwooLimKR** [faguodev/regularization_experiments#1]
Dear Authors,
Thank you for making this code available.

The README states that the JAR files were created by modifying Forclift’s code.
Does this mean that no_reg_lbfgs.jar is a direct compilation of Forclift’s original code?

Thank you,
-Seongwoo

**Comment by florian-chen** [comment]
Dear Seongwoo,
thank you for your interest in our work.

Yes, that's correct, no_reg_lbfgs.jar is pretty much a direct compilation of the original Forclift code.

All the changes we made to the Forclift code, including some other regularization methods that didn't make it into the paper, are also found here in my Forclift fork: https://github.com/faguodev/Forclift

Please let us know if you have any further questions.

Best,
Florian

**Comment by SeongwooLimKR** [comment]
Thank you for your kind response!
